### ISSUE TITLE
Firefox broken after xbps-install -Suv ; fixed with a small package re-install

### ISSUE THREAD

**Issue by sam-falvo** [void-linux/void-packages#10013]
### System

* xuname:  Void 4.19.29_1 x86_64 GenuineIntel uptodate rFFFF
* package:  firefox-65.0.1_2

### Expected behavior
Launching firefox via the shell or via i3 should, after some reasonable delay, produce a browser window.

### Actual behavior
No window is displayed when launched from i3.  When launched from the shell, the following error is produced:

```
[kc5tja@fomalhaut ~]$ hash -r
[kc5tja@fomalhaut ~]$ firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libvpx.so.5: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

### Steps to reproduce the behavior
1. Update system with sudo xbps-install -Suv and reboot to activate the latest kernel.
2. Open your favorite terminal in X11, Wayland, or other display server technology of your choice.
3.  Type "firefox".

### Steps taken to remediate
I've found what looks to be a related issue at https://github.com/void-linux/void-packages/issues/9408 ; however, the circumstances appeared to be different.  The way the error message is written, it looks like I already have libvpx.so.5 installed; however, it appears that it has an unresolved dependency in trying to find libxul.so.  This is strange to me, as I've confirmed that the file exists:
```
[root@fomalhaut lib]# ls -l /usr/lib/firefox/libxul.so
-rwxr-xr-x 1 root root 95707384 Mar  2 12:12 /usr/lib/firefox/libxul.so
```
When running ldd, however, I find that my assumptions are backwards:
```
[root@fomalhaut lib]# ldd /usr/lib/firefox/libxul.so
        linux-vdso.so.1 (0x00007fffbd7d5000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f25a34f1000)
...etc...
        libevent-2.1.so.6 => /usr/lib/libevent-2.1.so.6 (0x00007f25a1903000)
        libvpx.so.5 => not found
...etc...
```
It looks like libvpx.so.5 is, in fact, *not* installed on my system (anymore?):
```
[root@fomalhaut lib]# find /usr/lib -iname libvpx.so.5
[root@fomalhaut lib]# find /usr/lib -iname libvpx.so
[root@fomalhaut lib]#
```
However, the package database says that it *did* in fact install it:
```
[root@fomalhaut lib]# xbps-query -Rs vpx | grep "\*"
[*] libvpx5-1.7.0_3       VP8 and VP9 video codec (1.7 series)
[*] libvpx6-1.8.0_1       VP8 and VP9 video codec
```
I've tried removing and reinstalling the package, in the hopes that maybe it was some kind of hiccup encountered while running xbps-install -Suv:
```
[root@fomalhaut lib]# xbps-remove libvpx5 firefox
[root@fomalhaut lib]# xbps-install libvpx5
...
[root@fomalhaut lib]# xbps-query -Rs vpx | grep "\*"
[*] libvpx5-1.7.0_3       VP8 and VP9 video codec (1.7 series)
[*] libvpx6-1.8.0_1       VP8 and VP9 video codec
[root@fomalhaut lib]# xbps-install firefox
...
[root@fomalhaut lib]# firefox
```
At this point, I was successfully able to launch Firefox.

As to what caused the initial hiccup, I am at a loss to explain it.  However, I wanted to document my steps to remediation here in the hopes that others who might run into this problem can see the solution I used which worked for me.

Thanks for providing a great distribution, everyone, and have a great week!

**Comment by Piraty** [comment]
I experienced the same issue with firefox unable to find `libvpx`.
solved by force-reinstalling the package (`xi -f libvpx5`).
The reason for this issue is yet unknown to me

**Comment by Cogitri** [comment]
FWIW, I haven't experienced this, but maybe we should just revbump libvpx5

**Comment by Piraty** [comment]
i suspected an interupted update, as `xbps-pkgdb -a` marked libvpx5 inconsistent, but it seems to have a different cause if other people encounter the same issue

**Comment by Duncaen** [comment]
Don't revbump libvpx5 again, this doesn't solve the issue.

`libvpx5` gets installed first, then `libvpx` gets "updated" to the empty package and removes the symlinks it owned before.

xbps checks which files should be removed on updates and uses the `mtime` to verify if its the same file.

Since making builds more reproducible, both packages have the same `mtime` for all of its files (and symlinks) and the assumption that `mtime` can be used to check if files are obsolete is broken in many cases.

**Comment by tetsumaki** [comment]
Same here.
Fixed, for information:

```
$ cd /usr/lib
$ ls -lh | grep libvpx
-rwxr-xr-x  1 root root  2.2M Mar  7 06:29 libvpx.so.5.0.0
lrwxrwxrwx  1 root root    15 Feb 10 12:45 libvpx.so.6 -> libvpx.so.6.0.0
lrwxrwxrwx  1 root root    15 Feb 10 12:45 libvpx.so.6.0 -> libvpx.so.6.0.0
-rwxr-xr-x  1 root root  2.3M Feb 10 12:45 libvpx.so.6.0.0
$ sudo xbps-install -f libvpx5
$ ls -lh | grep libvpx
lrwxrwxrwx  1 root root    15 Mar  7 06:29 libvpx.so.5 -> libvpx.so.5.0.0
lrwxrwxrwx  1 root root    15 Mar  7 06:29 libvpx.so.5.0 -> libvpx.so.5.0.0
-rwxr-xr-x  1 root root  2.2M Mar  7 06:29 libvpx.so.5.0.0
lrwxrwxrwx  1 root root    15 Feb 10 12:45 libvpx.so.6 -> libvpx.so.6.0.0
lrwxrwxrwx  1 root root    15 Feb 10 12:45 libvpx.so.6.0 -> libvpx.so.6.0.0
-rwxr-xr-x  1 root root  2.3M Feb 10 12:45 libvpx.so.6.0.0
```

**Comment by AaronM04** [comment]
Just curious -- why was this closed? From reading the comments, it's not clear what actions were taken to resolve this issue.

**Comment by haunma** [comment]
I second @AaronM04's question.  I ran into this bug today during a fresh void install (firefox v69).  If the problem lies with upstream, or xbps itself, fine, but rationale should be given before closing the issue.  The fact that a workaround exists is really beside the point.  How can we resolve this?

**Comment by glitch-method** [comment]
I also just got this on a fresh install.

**Comment by Duncaen** [comment]
This has been fixed in xbps for a while now and is now released.
