### ISSUE TITLE
gcc-7.3.0_4 breaks dkms, other packages not pre-built

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#1134]
### System

* xuname:  
  Void 4.17.6_1 x86_64 GenuineIntel uptodate rFFFFFFF
* package:  
   gcc-7.3.0_4
   libgcc-7.3.0_4
   libgcc-devel-7.3.0_4
### Expected behavior
Successful load/link/compile
### Actual behavior
Errors, such as "cc1: error: incompatible gcc/plugin versions" , or undefined symbols?

Latest gcc update is causing build failures for multiple packages that require compiling/linking on the host computer (or rebuilding in response to other updates). This includes dkms modules such as nvidia-dkms or virtualbox-ose-dkms. In my case it also includes packages compiled from xbps-src. I compile my own version of compiz-git outside any xbps repository and that is also affected.

This is a DIFFERENT issue from the earlier one opened by me about nvidia on 32bit systems.

**Comment by pullmoll** [comment]
Should be solved with the kernel update. IMO we should really drop gcc plugins for Linux kernels.

**Comment by ruegerjr** [comment]
I respectfully request you re-open Void-linux issue #1134.  The newer kernel has indeed eliminated the "cc1: error: incompatible gcc/plugin versions"  error, but compiling with gcc-7.0.3_4 is still broken in Void. I get the following error with dkms:

make[1]: Entering directory '/usr/src/kernel-headers-4.17.9_1'
arch/x86/Makefile:184: *** Compiler lacks asm-goto support.. Stop.
make[1]: Leaving directory '/usr/src/kernel-headers-4.17.9_1'
make: *** [Makefile:79: modules] Error 2

As I understand it, this should not occur in versions of gcc > 4.5 or so.  I assume a regression in gcc-7.0.3_4?  Also, as before, compiling packages outside of dkms may appear to succeed, but errors occur when invoked, such as:

undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

Please note that gcc/gcc-devel still works perfectly in previous version "7.0.3_3" for BOTH old and new kernels.

**Comment by pullmoll** [comment]
I'd be really surprised if dropping support for libstdc++ GCC4 compatibility would lead to a regression in the compiler. After all **not** supporting GCC4 compatibility is the default.

What source are you trying to compile? I'd like to try to reproduce the error here.

**Comment by ruegerjr** [comment]
Apologies for the delay.  I am embarrassed to say that the errors I continued to receive appear to be the result of some corruption or dysfunction with my particular partition.  I found version mismatches between libssp and gcc/libgcc which should not have occurred with the methods I used to downgrade/upgrade packages during my testing, and I suspect other problems I have yet to uncover.

On an alternative Void partition on the same machine, the packages behave exactly as you expected. gcc-7.3.0_3 correctly builds dkms modules for void kernels through 4.17.6_1, and fails for kernel 4.17.9_1.
Conversely, gcc-7.4.0_4 fails to build modules for prior kernels, but succeeds for kernel 4.17..9_1.

I appreciate pullmoll's trust and willingness to reopen this issue at my request, and regret if I have abused that trust.  I am once again closing the issue. Thank you.

**Comment by jnbr** [comment]
Please check the output of `xbps-alternatives -g cc -l`.  In case `clang` is used, set it to `gcc` with `xbps-alternatives -s gcc`.
Probably same issue: https://github.com/voidlinux/void-packages/issues/14052

**Comment by redbird1f8** [comment]
Thank you! Now everything is working.

**Comment by jnbr** [comment]
> I respectfully request to re-open this issue because the GCC version distributed yesterday broke it again.

new kernels which fix the latest breakage are currently being built. Check for updates in a few hours
