### ISSUE TITLE
[TRACKING] glibc 2.36 (and gcc 12) build failures

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#39960]
https://vasilek.cz/logs/gcc12-glibc-filtered/bad/

These are new failures from a gcc 12 glibc 2.36 world rebuild, this list doesn't include failures already found in previous musl rebuilds (https://github.com/void-linux/void-packages/issues/39809, https://github.com/void-linux/void-packages/issues/39083). These can be caused by glibc 2.36 or gcc 12 if they are not available on musl.

- [x] EternalTerminal (#40663)
- [x] arb
- [x] avr-gdb
- [x] cabbage (#40885)
- [x] catch2
- [x] cereal
- [x] clementine
- [x] cpp-hocon (#40645)
- [x] cppcodec
- [x] criu
- [x] cross-arm-none-eabi-gdb (#40887)
- [x] embree
- [x] fakechroot
- [x] fakeroot (#40644)
- [x] gamemode
- [x] gatling
- [x] ghidra (1740a52acb42507f4d86cbc5e4de3e8e97147975)
- [x] libhugetlbfs
- [x] libknet1
- [x] libowfat
- [x] libstatgrab
- [x] lxc
- [x] lxcfs
- [x] mono
- [x] mtd-utils
- [x] mtree
- [x] nethack
- [x] openmw
- [x] pam_zfscrypt
- [x] partclone
- [x] pencil2d
- [x] rawtherapee (#40692)
- [x] soci
- [x] stepmania (#40783)
- [x] systemtap
- [x] tcc #40900 
- [x] tracebox (#40759)
- [x] wren-cli
- [x] xdm

fixed by rebuilding mk-configure
- [x] runawk
- [x] libmaa

fixed by using the glibc stable release branch instead of the 3.36 release
- [x] bootchart2
- [x] toybox
- [x] autofs
- [x] hwinfo
- [x] snapraid
- [x] x2goclient

**Comment by dkwo** [comment]
does the recent update to `arb` fix this?

**Comment by paper42** [comment]
> does the recent update to `arb` fix this?

yes, thanks for the comment

**Comment by kruceter** [comment]
`runawk` does not build on musl with the same result.

The problem lays with `mk-configure` which has to be revbumped with gcc 12.

mk-configure has a tendency to do its work only when it was built with a compiler of the corresponding version.

If compiled with GCC 10.2, it looks for `/usr/share/mk-configure/mk/mkc_imp.cc_gcc-10.2.1.mk` and/or `/usr/share/mk-configure/mk/mkc_imp.cxx_gcc-10.2.1.mk` depending if CC or CXX are used.

If used with GCC 12.2 without getting recompiled first, the utility looks for `/usr/share/mk-configure/mk/mkc_imp.cc_gcc-12.2.0.mk` and/or `/usr/share/mk-configure/mk/mkc_imp.cxx_gcc-12.2.0.mk` and finds none because it was never built with GCC 12.

Build failure with GCC 12 on musl (x86_64-musl):

[runawk.fail.txt](https://github.com/void-linux/void-packages/files/10025637/runawk.fail.txt)

mk-configure revbump + rebuild with GCC 12:

[mk-configure-rbmp-gcc12.txt](https://github.com/void-linux/void-packages/files/10025645/mk-configure-rbmp-gcc12.txt)

Now runawk builds as expected:

[runawk.txt](https://github.com/void-linux/void-packages/files/10025648/runawk.txt)

**Comment by wael444** [comment]
glibc upstream has been updated to solve this... void should be using that.

**Comment by paper42** [comment]
> glibc upstream has been updated to solve this... void should be using that.

@wael444 Do you have some more information about this? Solve what exactly? This looks like a problem with the mk-configure package that we should revbump.

**Comment by wael444** [comment]
https://vasilek.cz/logs/gcc12-glibc-filtered/bad/toybox.txt fixed by:
commit glibc 3e279192749cfcae4ceebb1f21a3275e677d0561: https://github.com/bminor/glibc/archive/3e279192749cfcae4ceebb1f21a3275e677d0561.tar.gz

just try this for glibc, some of the packages would succeed to compile

**Comment by oreo639** [comment]
Thanks.

**Comment by kruceter** [comment]
# cpp-hocon

Since I was not able to find Michal's logs about this package, I may include this one: [cpp-hocon_fail.txt](https://github.com/void-linux/void-packages/files/10049155/cpp-hocon_fail.txt)

Errors clearly indicate that `catch.hpp` is not found. Despite including `catch2` and fixing header inclusion to `catch2/catch.hpp`, adventures do not end here:

```
[50/68] Building CXX object lib/tests/CMakeFiles/libcpp-hocon_test.dir/concatenation_test.cc.o
FAILED: lib/tests/CMakeFiles/libcpp-hocon_test.dir/concatenation_test.cc.o
/usr/bin/g++ -DBOOST_ALL_DYN_LINK -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOCALE_DYN_LINK -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_WITHOUT_WCHAR_T -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DLEATHERMAN_I18N -DLEATHERMAN_LOGGING_NAMESPACE=\"puppetlabs.cpp-hocon\" -DLEATHERMAN_USE_LOCALES -DPROJECT_DIR=\"/builddir/cpp-hocon-0.3.0/build\" -DPROJECT_NAME=\"cpp-hocon\" -I/builddir/cpp-hocon-0.3.0/lib/inc -I/builddir/cpp-hocon-0.3.0/lib/tests/catch/include -Wextra -std=c++11 -Wall -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-unknown-pragmas -Wno-missing-field-initializers -Werror -Wno-maybe-uninitialized -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -fdebug-prefix-map=/builddir/cpp-hocon-0.3.0/build=. -MD -MT lib/tests/CMakeFiles/libcpp-hocon_test.dir/concatenation_test.cc.o -MF lib/tests/CMakeFiles/libcpp-hocon_test.dir/concatenation_test.cc.o.d -o lib/tests/CMakeFiles/libcpp-hocon_test.dir/concatenation_test.cc.o -c /builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc
In file included from /builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc:1:
/builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc: In function 'void C_A_T_C_H_T_E_S_T_0()':
/builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc:300:9: error: cannot declare reference to 'struct hocon::config_exception&', which is not a typedef or a template type argument
  300 |         REQUIRE_THROWS_AS(
      |         ^~~~~~~~~~~~~~~~~
/builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc:300:9: error: 'const' qualifiers cannot be applied to 'hocon::config_exception&'
/builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc:309:9: error: cannot declare reference to 'struct hocon::config_exception&', which is not a typedef or a template type argument
  309 |         REQUIRE_THROWS_AS(
      |         ^~~~~~~~~~~~~~~~~
/builddir/cpp-hocon-0.3.0/lib/tests/concatenation_test.cc:309:9: error: 'const' qualifiers cannot be applied to 'hocon::config_exception&'
[51/68] Building CXX object lib/CMakeFiles/libprojectsrc.dir/src/config_value_factory.cc.o
[52/68] Building CXX object lib/tests/CMakeFiles/libcpp-hocon_test.dir/config_document_parser_test.cc.o
[53/68] Building CXX object lib/CMakeFiles/libprojectsrc.dir/src/values/config_concatenation.cc.o
ninja: build stopped: subcommand failed.
=> ERROR: cpp-hocon-0.3.0_4: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:93
```

This problem persists with musl-based environment the same way, too.

**Comment by 7r3nzy** [comment]
`mono` builds with gcc-12, I think someone must've fixed this already

**Comment by paper42** [comment]
done
