### ISSUE TITLE
Steam: Easy Anti-Cheat does not work under Void

### ISSUE THREAD

**Issue by Cynosphere** [void-linux/void-packages#41388]
### Is this a new report?

Yes

### System Info

Void 6.0.15_1 x86_64 AuthenticAMD notuptodate FFFFFFFF

### Package(s) Affected

steam-1.0.0.75_2 (theoretical)

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1368284488
https://github.com/void-linux/void-packages/pull/34902#issuecomment-1255715853
https://github.com/ValveSoftware/Proton/issues/6051

### Expected behaviour

Games using Easy Anti-Cheat run fine.

### Actual behaviour

Games using Easy Anti-Cheat seem to not initialize Easy Anti-Cheat properly.

### Steps to reproduce

VRChat:
1. Launch game through Steam
2. Login if fresh install
3. Be greeted with "Can't Travel" screen explaining Easy Anti-Cheat hasn't been initialized.

Apex Legends:
1. Launch game through Steam
2. Wait to get to the main menu
3. Be greeted with Engine Error message box saying "Easy Anti-Cheat Hash Catalogue not found"

**Comment by oreo639** [comment]
Comment #2 is not relevant to the issue, if you go further, you will see that the issue is that while I was testing with a patched glibc I wasn't using a patched glibc-32bit (hence why it wasn't working).

I tested with Multiversus and that works for me.

You can try `xbps-install -Sf glibc glibc-32bit` to make sure you are using the version from the repos and not an old local build.

**Comment by oreo639** [comment]
When did you first run into this issue and was it working for you before the glibc 2.36 update?

**Comment by oreo639** [comment]
Did you follow `cat /usr/share/doc/steam/README.voidlinux`?

**Comment by oreo639** [comment]
Can you join #voidlinux on irc/matrix?

**Comment by oreo639** [comment]
The Apex Legends legends issue was solved by using Proton 6.3.
idk about the VRChat issue though.

**Comment by oreo639** [comment]
I can confirm that Apex Legends doesn't work. I can also confirm that DT_HASH is present in glibc so it shouldn't be related to that:
This can be confirmed using:
`readelf -e /usr/lib/libc.so.6`
`readelf -e /usr/lib32/libc.so.6`
Both have `.gnu.hash` and `.hash` (whereas most binaries should just have `.gnu.hash`)

**Comment by oreo639** [comment]
You can try using `strace -f` to see where it exits?

**Comment by oreo639** [comment]
> Sorry I wasted your time, as per usual that it seems to be with me trying to interact with anything on GitHub...

You didn't waste my time. I don't personally play anticheat games and many of them require special accounts to play so idk if they worked before or now, all I know is that Multiversus doesn't get to the sign-in screen without DT_HASH and it does with DT_HASH so I imported the patch.
Just keep in mind that almost if not everyone here are volunteers and also I'd imagine being difficult to debug it part of the point of an Anticheat.

**Comment by oreo639** [comment]
I think I found the log for EAC, it should be in `$HOME/.local/share/Steam/steamapps/compatdata/1172470/pfx/dosdevices/c:/users/steamuser/AppData/Roaming/EasyAntiCheat`
Here are my logs:
https://gist.github.com/oreo639/7d3d430308bb604efca6a47952c64df9

**Comment by oreo639** [comment]
I found logs at `$HOME/.local/share/Steam/steamapps/compatdata/1172470/pfx/dosdevices/c:/users/steamuser/AppData/Roaming/EasyAntiCheat`
When running it with proton 6.3 it shows the following error `Connect result: Couldn't resolve host name (6) Response Code: 0 Destination IP: Unavailable`
When using proton experimental the logs here indicate no error (although the "Easy Anti-Cheat Hash Catalogue not found" error still show up when trying to start the game).

There are also logs generated at `~/.cache/com.epicgames.easyanticheat/154` when using proton expiremental which shows the following error: `[Connection] Connect result: No error (0) Response Code: 200 Destination IP: 2600:9000:234c:9000:10:ae80:c5c0:93a1`

**Comment by Naia-love** [comment]
Hello, have same troubles here, on Void too, can't play apex or vrchat, I can play Elden Ring but in offline only. 
For Apex replacing the EAC dll/so by the one present in the proton EAC runtime make the game goes past the "Easy Anti-Cheat Hash Catalogue not found", launching properly, accessing to the loby and all, but after a while it'll kick you out saying that EAC isn't running.

I also want to report that EAC isn't the only thing acting strange on Void, [steamvr](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/511#issue-1210110962) is too

**Comment by paper42** [comment]
reopening because this is not fixed

**Comment by Johnnynator** [comment]
Actually the issue seems to be the compination of eac and our glibc, did setup a quick chroot and changing the glibc to the one from arch satisfies eac, using the void one doesn't :shrug:

**Comment by Naia-love** [comment]
what is very strange is that: 
- I was using glibc 2.32 until now (which *isnt* a version of glibc known for troubles with EAC afaik)
- I just upgraded to 2.36, which is known to be problematic *but* that seems to be patched: https://github.com/void-linux/void-packages/tree/master/srcpkgs/glibc/patches

**Comment by ahesford** [comment]
I've read through some of the links on this page and, transitively, an essay at https://maskray.me/blog/2022-08-21-glibc-and-dt-gnu-hash that leaves me wondering:
1. Why we carry a patch attempting to revert the linker change contrary to our usual deference to upstream. They have been aware of this problem for months and are apparently uninterested in the issue or reverting the change.
2. Why this issue isn't closed as WONTFIX with a note that EAC needs to fix its shit. The patch doesn't fix Void-packaged software, it fixes proprietary software fetched optionally by one of our packages. Furthermore, as already noted, there are alternatives like flatpak while people bother the EAC people to fix what broke.

**Comment by oreo639** [comment]
> Why we carry a patch attempting to revert the linker change contrary to our usual deference to upstream. They have been aware of this problem for months and are apparently uninterested in the issue or reverting the change.

I assume you are referring to:
https://sourceware.org/pipermail/libc-alpha/2022-August/141304.html

> At present I would not make any changes to glibc. I would close bug 29456
as RESOLVED/WONTFIX. I'm open to hearing from the EPIC EAC developers 
if they have a case to make about DT_HASH.

Carlos later said:
https://sourceware.org/pipermail/libc-alpha/2022-September/142353.html

> The fix is available in version 1.15.2 of the EOS SDK and in the new
> corresponding version of the anti-cheat module. This was released in August.
> 
> Fixing this issue though requires several steps that need to be taken by the
> developers of the game itself.
>... 
>Looking across the distributions some of them are carrying a revert that adds
>back DT_HASH. Therefore I think it would help the distributions and add
>back DT_HASH support for a longer period of time before final removal.
>
>I don't think this will solve all the problems, but I will work to test out
>the revert on my Fedora system.

Carlos added a temporary revert for DT_HASH in Fedora:
https://src.fedoraproject.org/rpms/glibc/c/a9713abfbd4db4350fbc201e4d5cd6ddc36cfd27?branch=f37

**Comment by ahesford** [comment]
I'm referring to the fact that the upstream issue at https://sourceware.org/bugzilla/show_bug.cgi?id=29456 remains open and unassigned five months after it was reported. 

Whether other distributions carry a patch to revert the change is irrelevant here. Void favors upstream decisions and eschews patches unless they are backport as of upstream changes or fix issues introduced specifically by our packaging. This is neither. Upstream made a change to drop support for DT_HASH and continues to stand by it. We should be uninterested in fixing this problem until either upstream reverts the patch (in which case we can backport it if we don't want to wait for the next release) or EAC is fixed to support the glibc change (in which case the problem goes away entirely).

This is not our problem to fix.

**Comment by datwolfyy** [comment]
It is not a "violation" of upstream decisions/policies to use the provided option to include DT_HASH, since they give you the option to compile it in.

**Comment by dsemy** [comment]
> I'm referring to the fact that the upstream issue at https://sourceware.org/bugzilla/show_bug.cgi?id=29456 remains open and unassigned five months after it was reported.
> 
> Whether other distributions carry a patch to revert the change is irrelevant here. Void favors upstream decisions and eschews patches unless they are backports of upstream changes or fix issues introduced specifically by our packaging. This is neither. Upstream made a change to drop support for DT_HASH and continues to stand by it. We should be uninterested in fixing this problem until either upstream reverts the patch (in which case we can backport it if we don't want to wait for the next release) or EAC is fixed to support the glibc change (in which case the problem goes away entirely).
> 
> This is not our problem to fix.

This issue isn't caused because support for DT_HASH was dropped though; as other comments indicate, Easy Anti Cheat has been broken on Void since at least glibc 2.32.  After all, the current glibc package does contain this patch and yet EAC is still broken.  IOW, discussion about this patch is off-topic and would be better suited in a separate issue IMO.

I'm posting this mainly because as a user your comment (being the last one in the chain) made me think that the issue is related to the glibc 2.36 update, when it isn't actually.  This discouraged me from attempting to troubleshoot it on my own, which seems counter-productive to me (although admittedly I didn't get very far when I did try troubleshooting on my own).  This is significant, as currently Void is the only distribution I am aware of in which EAC is broken despite the aforementioned patch being applied.

In any case, I would very much like to see this issue fixed, and I would be glad to help with any testing (I own Elden Ring and Fall Guys on Steam, both of which use EAC unfortunately).

BTW, I don't use the Steam Flatpak since I also use Steam as a launcher for emulated games - setting this up is very complicated with the Flatpak version (Flatpak in general is way too complicated IMO, so I'd prefer to avoid it  if possible).

**Comment by numfin** [comment]
How i can install eac supported version of glibc so i can play games?

**Comment by 42plague** [comment]
I'm writing this just to draw more attention to this bug.
Despite having a patch, EAC games still won't run (Apex Legends in my case).
Other distributions run it without problems, so it's definitely a Void bug.

**Comment by Naia-love** [comment]
small update on my end, 
especially about https://github.com/void-linux/void-packages/issues/41388#issuecomment-1369014128
steamvr was probably not a void issue, just steamvr breaking up on some specific configuration im guessing. I was able to run just fine last public release, use it with alvr, get in vr, even launch vrchat without any troubles.
Tho so vrchat didnt run properly because EAC is still broken unfortunaly :v

**Comment by fanyx** [comment]
bumping @oreo639 

Were you or another member of the Void team able to find any leads on this?
I've found the "Hash catalogue not found" error to be present in Dead by Daylight as well.
Fall Guys works without any issues though.

**Comment by nonchip** [comment]
soo i have multiple EAC games, most of which don't run (for years now, so pretty sure not DT_HASH related) despite *everyone* telling me they should, the fact that steamflatpak seems to help some people points at some other library being borked but i'm not sure how to investigate further, please someone tell me how i can help figure this out finally? :(

**Comment by Requion** [comment]
While search for information on this issue, i stumble upon this discussion in the Gentoo forum which is marked as solved.
https://forums.gentoo.org/viewtopic-p-8703494.html?sid=92410f4f29b13814bbf566faa6d38886#8703494

I've seen that this is a bit older and i don't have enough experience to see if this might help or is relevant at all anymore. I tried to add this patch and build locally but this either didn't work or i just did it wrong.

**Comment by nonchip** [comment]
@Requion pretty sure that's about the .hash/.gnu.hash sections @oreo639 already ruled out as a potential cause.

**Comment by oreo639** [comment]
Btw, just I removed the patch since I couldn't figure out how to make EAC work regardless of what flags I used and I am not aware of anything fixed by the DT_HASH patch (feel free to let me know if there are breakages after upgrading glibc, e.g. worked before updating but not afterwords).

If you still want to test with DT_HASH enabled you can enable it by copying these two lines before the `make` call in `do_buld()` in the glibc template:
https://src.fedoraproject.org/rpms/glibc/blob/ca9e6ac79501d9ee8eeaf795c5764d8733534910/f/glibc.spec#_1219

> Were you or another member of the Void team able to find any leads on this?

Just to clarify, I am just a Void user and not a part of the void-team organization. Also, no I couldn't figure out what the issue was.

**Comment by dexgs** [comment]
I have tried intermittently to fix this myself by getting the configure arguments as close to those on Arch and Fedora as possible (as well as numerous other changes) and this hasn't worked.

As Johnnynator said previously, EAC works as expected if you use the build from Arch Linux. There is a problem with Void's build of glibc that is not present on other distributions.

Given that no progress has been made in the year since this issue has been opened, and that those affected stand basically 0 chance of resolving this on their own, is it possible to reach out to knowledgeable glibc maintainers from other distributions to shed some light on this problem?

It's good that users can circumvent this problem using flatpak or another distribution's glibc, but this is far from ideal.

**Comment by okawo80085** [comment]
Well, updating `glibc` to the recently merged 2.38_2 version that has the fix for EAC to not crash brings it back to life, and it does start now, only issue is that it fails with a network error now x)
![image](https://github.com/void-linux/void-packages/assets/43695253/c64abcac-f96f-4654-8113-4ee7c979ea84)
Which is weird, cuz looking at EAC logs it finishes the download, but the callback throws an error?
```
[2024.01.01-13.37.29] Download Progress: 90
[2024.01.01-13.37.29] Download Progress: 100
[2024.01.01-13.37.29] Download Progress: 100
[2024.01.01-13.37.29] Download Progress: 100
[2024.01.01-13.37.29] Download Progress: 100
[2024.01.01-13.37.29] [Connection] Connect result: No error (0) Response Code: 200 Destination IP: 18.244.146.77
[2024.01.01-13.37.29] Download Progress: 100
[2024.01.01-13.37.29] [EAC Callback] Code: 509. Message: 'Unexpected error. (#1)'.
```
Not sure if its related to the new `glibc` update, it did disable cryptography functionality from `glibc` and instead moved it to `libxcrypt` , you can find more in the `glibc` package MR https://github.com/void-linux/void-packages/pull/45501

I wonder if preloading steam with `libxcrypt` will help it :thinking:

**Comment by oreo639** [comment]
libxcrypt is specifically for encrypting passwords. For most cryptography, openssl is used. It is likely unrelated.
Afaict libcrypt.so is not used or checked by EAC.

**Comment by okawo80085** [comment]
Well idk it doesn't like then, all the links its checking are fine, i can even see in the logs from EAC that it finishes the download it was doing, but it still fails with that error :woman_shrugging:

**Comment by HO5DTOAT** [comment]
I am getting a similar EAC error when trying to run [Brawlhalla](https://store.steampowered.com/app/291550/Brawlhalla/). I tried both Steam with Proton experimental as well as Lutris with Ubisoft Connect and got the same error. This started happening after the glibc 2.38 update.
![image](https://github.com/void-linux/void-packages/assets/101270121/ff9db577-b009-4740-922b-3afd192be25e)


In the EAC logs folder of the game (`~/.local/share/Steam/steamapps/compatdata/291550/pfx/drive_c/users/steamuser/AppData/Roaming/EasyAntiCheat/2a5901f5be6545b39f551a92214978d6/e7e719b170b74c18b89ba4f3cccd4fdc/loader.log`) , I can see the download success followed by the error message.

```
[2024.01.08-13.09.03] Download Progress: 99
[2024.01.08-13.09.03] Download Progress: 99
[2024.01.08-13.09.03] Download Progress: 99
[2024.01.08-13.09.03] Download Progress: 100
[2024.01.08-13.09.03] Download Progress: 100
[2024.01.08-13.09.03] Download Progress: 100
[2024.01.08-13.09.03] Download Progress: 100
[2024.01.08-13.09.03] [Connection] Connect result: No error (0) Response Code: 200 Destination IP: 18.66.57.4
[2024.01.08-13.09.03] Download Progress: 100
[2024.01.08-13.09.03] [EAC Callback] Code: 507. Message: 'Failed to load the anti-cheat module.'.
```

In my system which has the glibc 2.38. I can see only the `.gnu.hash` entries.
![image](https://github.com/void-linux/void-packages/assets/101270121/30bd4e74-6170-4d25-b019-af72bfd7f18f)

Checking the commit history for glibc. it seems the patch that enabled DT_HASH is not present in the 2.38 commit https://github.com/void-linux/void-packages/commit/ee93adc0af49c8f3825dff7e3c6c7dbc40ef4b70. Could that be causing the issue again?
![image](https://github.com/void-linux/void-packages/assets/101270121/f5097ebf-ecaf-45fa-b5b6-46c211890658)

**Comment by oreo639** [comment]
Thank you, I can confirm that Brawlhalla is an EAC game that works on Void's glibc with DT_HASH.

**Comment by oreo639** [comment]
> EDIT: in case this goes anywhere, the one interesting thing I found that is not already mentioned is that arch's libc.so.6 has a `.gnu_debuglink` section while void's does not. void also has a `.plt.got` section while arch has a `.plt.sec` section.

I got compiled a glibc in xbps with the same sections as Arch Linux (same flags and same stripping) and it still errors. `diff -rup <(readelf -S libc.so.6 | grep "\[[0-9]*\]" | sed -r 's/([^.]*)(\.[^ ]*)(.*)/echo "\2"/ge') <(readelf -S /usr/lib/libc.so.6 | grep "\[[0-9]*\]" | sed -r 's/([^.]*)(\.[^ ]*)(.*)/echo "\2"/ge')`

I tested further using bwrap and overlayfs, and launching steam using Arch Linux's libc.so.6 (nothing else seemed to affect anything) does allow EAC games to work (with DT_HASH in the system glibc ofc) even when swapping the libc.so.6 with the system one before launching the game. I am still not sure what the error is.

**Comment by Sapein** [comment]
That is...exceedingly weird. The only thing I can think of is there's some weird difference that's unrelated to the sections that is either incidentally environmental or is expected that Void *doesn't* have...not sure how you would go about solving that though tbqh...

**Comment by okawo80085** [comment]
Maybe lets try take flatpak's glibc and run and compare it to upstream glibc? Cuz like if flatpak steam works fine lets check what they are doing different compared to our environments

**Comment by dexgs** [comment]
> That is...exceedingly weird. The only thing I can think of is there's some weird difference that's unrelated to the sections that is either incidentally environmental or is expected that Void _doesn't_ have...not sure how you would go about solving that though tbqh...

It's something caused by the glibc binary itself. As discussed previously, if you swap out glibc with the files from arch linux, EAC works as expected

**Comment by nonchip** [comment]
@dexgs are we **sure** on that though? definitely not how i'd read @oreo639's last comment (or literally any of the others trying to compare/replace those), and all @Johnnynator said was they "set up a chroot" without details as to *what* was setup *how*, and those usually contain more than just a single `.so`.

and we've already proven it's unrelated to the DT_HASH thing, the thing everyone keeps blaming here for no reason whatsoever.

**Comment by fanyx** [comment]
Do any signs point to anything other than glibc?
It does get more and more nebulous now that people have tested newly compiled, other distro's, sandboxed, etc. libc's

**Comment by uniboi** [comment]
I was able to work around the issue before glibc 2.37 was availabe via xbps by compiling the glibc version I needed and running steam like this `D_LIBRARY_PATH=/opt/glibc-2.37-32bit/lib steam`.
Today I finally updated glibc to 2.38 with xbps-install but I still get the Hash Catalogue not found error for EAC games.
My workaround stopped working too, the steam UI now segfaults lol.

**Comment by dexgs** [comment]
> @dexgs are we **sure** on that though?

Yes, I managed to get EAC to work by taking the `ld-linux-x86-64.so.2` and `libc.so.6` binaries from Arch Linux and putting them into `/usr/lib`

I don't recommend doing this because it is very easy to break your install this way, but it confirms that it is specifically Void's glibc binaries which cause the problem.

**Comment by nonchip** [comment]
> `ld-linux-x86-64.so.2`

...isn't glibc, so that's good to know. do you want to maybe elaborate on the reasoning / your findings? we got multiple conflicting findings about "arch's glibc" (and nothing as to how that even differs from ours), one person claiming that simply compiling with pretty much default options fixes everything *after* another says that compiling with the options arch itself uses *doesn't* fix anything. and now you're answering "can we be sure it's that exact issue with that exact file" with "yeah totally because i replaced a different one and it works now", that honestly doesn't sound like it answers anything :P

**Comment by dexgs** [comment]
No, sorry. I picked those two after asking @Johnnynator what he did, maybe he can explain why in more detail.

You're right that maybe the problem is caused by `ld-linux` but from what I remember, the system won't boot if the loader doesn't match `libc.so`, so there's no easy way to test "just" `libc.so`. I could be wrong, but I'm pretty sure this is the minimum files that can be taken from Arch while still having a bootable system.

My point about it being fixed with "just" the 2 files from Arch is that it demonstrates that the problem is not some environmental difference between Void and other distros, it is specifically an issue with Void's build of glibc.

As per the conflicting reports, I think one person is saying that they modified the xbps template to match Arch's build options as closely as possible while the other is saying they did a build of glibc without creating an xbps package.

Based on this, it seems like maybe the problem is caused by some automatic step in xbps (some symbol gets stripped which shouldn't, or something like that).

**Comment by SpidFightFR** [comment]
> Well, updating `glibc` to the recently merged 2.38_2 version that has the fix for EAC to not crash brings it back to life, and it does start now, only issue is that it fails with a network error now x) ![image](https://private-user-images.githubusercontent.com/43695253/293589005-c64abcac-f96f-4654-8113-4ee7c979ea84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzcwODQsIm5iZiI6MTcwNjEzNjc4NCwicGF0aCI6Ii80MzY5NTI1My8yOTM1ODkwMDUtYzY0YWJjYWMtZjk2Zi00NjU0LTgxMTMtNGVlN2M5NzllYTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIyNTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjI3ODM2NGMyZmQ1ZWVjZTU5MjM3MTg5OGMwNWI1NGU1YjYxODI1NjhmNDUyY2RjZTcyNWQ3MzMyZGM2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ig3-nqutrTJjnzF68zTyovifcjZ2c-5wpqFPo87ldW8) Which is weird, cuz looking at EAC logs it finishes the download, but the callback throws an error?
> 
> ```
> [2024.01.01-13.37.29] Download Progress: 90
> [2024.01.01-13.37.29] Download Progress: 100
> [2024.01.01-13.37.29] Download Progress: 100
> [2024.01.01-13.37.29] Download Progress: 100
> [2024.01.01-13.37.29] Download Progress: 100
> [2024.01.01-13.37.29] [Connection] Connect result: No error (0) Response Code: 200 Destination IP: 18.244.146.77
> [2024.01.01-13.37.29] Download Progress: 100
> [2024.01.01-13.37.29] [EAC Callback] Code: 509. Message: 'Unexpected error. (#1)'.
> ```
> 
> Not sure if its related to the new `glibc` update, it did disable cryptography functionality from `glibc` and instead moved it to `libxcrypt` , you can find more in the `glibc` package MR #45501
> 
> I wonder if preloading steam with `libxcrypt` will help it 🤔

I thought i was going crazy there... So it is a glibc problem specific to void ?

**Comment by nonchip** [comment]
@SpidFightFR yknow, it generally helps not to copypaste a 20+ line comment wholesale just to ask a single *obvious* and already answered *in the comment(s) right above yours* question? especially if the comment you chose to copypaste is pretty much exclusively outdated information/speculation from before we knew more about the issue? for general sanity sake and such.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/f36d21c5a25e24a15a740b83f0847956a1c1b146

**Comment by nonchip** [comment]
@classabbyamp https://github.com/void-linux/void-packages/issues/41388#issuecomment-1368376502

**Comment by nonchip** [comment]
btw i just got an arch glibc (`2.38-7` pacman) to compare to ours (`2.38_4` xbps), so here's a diff from their to our sections:

```diff
--- ARCH
+++ VOID

@@ GLIBC @@

-.gnu.version_r
-.plt.sec
+.plt.got
-.stapsdt.base
-.note.stapsdt
-.gnu_debuglink
+.debug_aranges
+.debug_info
+.debug_abbrev
+.debug_line
+.debug_str
+.debug_line_str
+.debug_loclists
+.debug_rnglists
+.symtab
+.strtab

@@ LD-LINUX @@

-.relr.dyn
-.stapsdt.base
-.note.stapsdt
-.gnu_debuglink
+.debug_aranges
+.debug_info
+.debug_abbrev
+.debug_line
+.debug_str
+.debug_line_str
+.debug_loclists
+.debug_rnglists
+.symtab
+.strtab
```

**Comment by nekopsykose** [comment]
```
-.plt.sec
+.plt.got
```

the former is from -fcf-protection (iirc). arch has that in default cflags. probably doesn't matter, but you can rebuild passing that and see

```
-.stapsdt.base
-.note.stapsdt
```

this is --enable-systemtap and also probably doesn't matter

```
-.gnu_debuglink
```

this is for split debuginfo (here it's not split)

```
-.gnu.version_r
```

this is a symver thing. might matter, but this one is optional https://maskray.me/blog/2020-11-26-all-about-symbol-versioning


```
-.relr.dyn
```

this is ldflags -Wl,-z,pack-relative-relocs which arch now enables and most likely makes no difference (very recent from arch side)


overall it might not be related to those at all

**Comment by oreo639** [comment]
I already tested those: https://github.com/void-linux/void-packages/issues/41388#issuecomment-1884242338

**Comment by nonchip** [comment]
@nekopsykose thanks for your insight, my current best bet is on `.gnu.version_r`, because it's very much **not** optional according to LSB so there's a decent chance a "reasonable person" (and even an unreasonable ~~malware~~*anticheat* developer) might expect it.

@oreo639 i know you already did some tests, but you didn't show the details, and a lot of various quality levels of info are around on the googles about this topic, so i figured it doesn't hurt to start collecting some facts to make sure we're on a similar page to rule out or home in on the potential causes.

**Comment by nekopsykose** [comment]
> I already tested those: 

ah right, not any of those then, sorry for the noise :)

**Comment by okawo80085** [comment]
Lmfaoooooooooo, so with `glibc-2.38_4`, current latest upstream version of glibc and Proton Experimental, EAC doesn't crash anymore, BUT it kicks you from game like a minute or so after start of the match cuz it fails anticheat authentication x)
Gonna try with some other proton versions in a bit, but really not sure where to start with the failed authentication stuff, cuz there is nothing wrong in the eac logs now :/

**Comment by okawo80085** [comment]
Ohhhhh, looking at the steam client terminal output when i run the game with GE-Proton8.27, found this gem
```

LogActor: Warning: SetReplicates called on non-initialized actor BP_Projectile_M18_C_2147460702. Direct
ly setting bReplicates is the correct procedure for pre-init actors.


LogNet: Warning: UNetDriver::ProcessRemoteFunction: No owning connection for actor BP_Character_Player_
C_2147476777. Function ServerSetCameraIsTargetingKillLocation will not be processed.


LogINSPlayerController: Display: Kicked by server: Anti-Cheat: Authentication timed out (1/2).
LogNet: Error: UEngine::BroadcastNetworkFailure: FailureType = ConnectionLost, ErrorString = Your conne
ction to the host has been lost., Driver = GameNetDriver IpNetDriver_2147477057
LogNet: Warning: Network Failure: GameNetDriver[ConnectionLost]: Your connection to the host has been l
ost.
LogINSParty: Warning: EndCurrentMatch : Reset latest party data.
LogStreaming: Display: FlushAsyncLoading: 1 QueuedPackages, 0 AsyncPackages
LogLoad: Warning: UINSGameInstance::OnPreLoadMap: Invalid NextURL, loading /Game/Maps/Utility/Entry
LogEOSAntiCheat: Display: EndSessionClient : Result : (EOS_InvalidParameters)
LogEOSAntiCheat: Display: BeginSessionClient : Result : (EOS_InvalidParameters)

```
Anyone seen anything like this before?

**Comment by Naia-love** [comment]
> Lmfaoooooooooo, so with `glibc-2.38_4`, current latest upstream version of glibc and Proton Experimental, EAC doesn't crash anymore, BUT it kicks you from game like a minute or so after start of the match cuz it fails anticheat authentication x)
> Gonna try with some other proton versions in a bit, but really not sure where to start with the failed authentication stuff, cuz there is nothing wrong in the eac logs now :/

Have you tried with more than one game ? (that you know it behavior before said update of glibc) or your game got updated? 
because what you're discribing was already something that was happening on some game (ie Vrchat, and that for at least as long as i started contributing to this issue)
for apex legend iirc it'd happen if you'd move manually the eac library from the proton eac inside the game folder

**Comment by nonchip** [comment]
> Anyone seen anything like this before?

@okawo80085 yes, that's the server kicking you for not passing the EAC check, that's what this whole issue is about :D

the crash was just a temporary side effect of it going *even* wronger than usual. or like @Naia-love suggests it might be just the game or proton having been crashy with EAC not even to blame for that part.

**Comment by okawo80085** [comment]
Well damn, i ran out of time to test with anything else yesterday, was testing with Insurgency Sandstorm, gonna try to test with a few more EAC games today

**Comment by Dekomoro** [comment]
According to an Arch Linux commit(https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/83899c6e216ef04a56f16faaa19fcbf84bd0f799) valve has reported all affected easy anti cheat titles to be patched to not require -hash-style=both.

**Comment by nonchip** [comment]
@Dekomoro yup that confirms the theory we already had that the hash thing is unrelated, because (in my and some others' experience above) EAC *never* really worked on void even tho the hash change only happened last year :P

**Comment by Naia-love** [comment]
> @Dekomoro yup that confirms the theory we already had that the hash thing is not the main cause, because (in my and some others' experience above) EAC *never* really worked on void even tho the hash change only happened last year :P

not exactly
im sure it worked for a while, 
but it definitively broke before the glibc hash change

**Comment by nonchip** [comment]
@Naia-love wait you're literally one of the sources supporting that conclusion :grin: 
what exactly do you mean by "i'm sure"? like are you guessing or reporting? because i for one have used void-glibc since the release of proton/EAC, and it *never* worked.

**Comment by Naia-love** [comment]
huh?
okay my memory may be wrong then
i recall playing apex on void without using flatpak
but yea been too much time could have been on another distro ig

**Comment by Naia-love** [comment]
I confirm, going through convo with freinds, at least apex did work for a while

**Comment by nonchip** [comment]
@Naia-love keep in mind plenty games also release/betatest/etc without malware and only choose to become a broken mess for no decent reason *after* "1.0 release" or "official sale" or whatchamacallit. maybe it used to work because it simply didn't care yet? :D

also apex specifically broke and unbroke their own `anticheat.so` about 20 times so far with what can only be explained by people with zero clue pushing the wrong "release to live without any testing" button, usually then followed by an accidental autoban of the whole customer base, so honestly no idea what they're doing/how reliably/correctly they even use EAC.

**Comment by Naia-love** [comment]
> @Naia-love keep in mind plenty games also release/betatest/etc without malware and only choose to become a broken mess for no decent reason _after_ "1.0 release" or "official sale" or whatchamacallit. maybe it used to work because it simply didn't care yet? :D

that not impossible ig, but it do have eac since release, so well xD 
but unfortunaly I havent played any other game with eac at that time (or i cant recall at least), any other eac game i played was after it broke.

> also apex specifically broke and unbroke their own `anticheat.so` about 20 times so far with what can only be explained by people with zero clue pushing the wrong "release to live without any testing" button, usually then followed by an accidental autoban of the whole customer base, so honestly no idea what they're doing/how reliably/correctly they even use EAC.

yes I remember that, most of time just grabbing the eac lib from the proton folder would work tho

**Comment by nonchip** [comment]
@Naia-love do you happen to remember when abouts that was? could be worth comparing the versions we had back then, maybe we also accidentally unbroke our libc for a while without realizing and rebroke it since :'D

**Comment by Naia-love** [comment]
> @Naia-love do you happen to remember when abouts that was (something like "summer last year" should be accurate enough)? could be worth comparing the versions we had back then, maybe we also accidentally unbroke our libc for a while without realizing and rebroke it since :'D

around start of 2022

**Comment by okawo80085** [comment]
Well, i decided to try comparing the same game on flatpak steam vs native steam package.
When using native package steam still the same anti cheat validation failed in Insurgency Sandstorm
```
LogEOSAntiCheat: Display: EndSessionClient : Result : (EOS_InvalidParameters)
LogEOSAntiCheat: Display: BeginSessionClient : Result : (EOS_InvalidParameters)
```
However when using flatpak steam, it works fine??? It also dumps these logs
```
LogEOSAntiCheat: Display: EndSessionClient : Result : (EOS_NotConfigured)
LogEOSAntiCheat: Display: BeginSessionClient : Result : (EOS_Success)
```
So im starting to have a feeling that this might be somehow tied into the native steam package as well...

**Comment by Naia-love** [comment]
> Well, i decided to try comparing the same game on flatpak steam vs native steam package.
> When using native package steam still the 
> So im starting to have a feeling that this might be somehow tied into the native steam package as well...

theres very little to no chance its that
flatpak use its own system lib (i dont wanna say bs as i dont know how it exactly work, but its kinda like if you do a chroot with others libs, like if you're on musl and do a glibc chroot of void, steam will work inside the glibc chroot.
and btw steam also work on musl void with flatpak)
so as it useit own glibc, if its indeed the  glibc void build the culprit (which we are like asfar i understood the thread, pretty sure), well its fiked cuz it use it own mot bugged

**Comment by okawo80085** [comment]
Well, how about we take a look at how flatpak builds their system lib and how it differs from ours

**Comment by Naia-love** [comment]
> Well, how about we take a look at how flatpak builds their system lib and how it differs from ours?

we are already doing so with arch

**Comment by classabbyamp** [comment]
flatpak does not use the system glibc. it is a container fully independent of the system

**Comment by okawo80085** [comment]
> flatpak does not use the system glibc. it is a container fully independent of the system

Well yeah, but its not like its built from some magical source, the steam package manifest can be found [here](https://github.com/flathub/com.valvesoftware.Steam/tree/beta)
And last time i checked freedesktop's stuff is also open source.

I started to look through it, and a few things i already noticed is that void's native package for steam is missing some deps compared to the stuff that flatpak is installing.

**Comment by okawo80085** [comment]
Also worth taking a look at what this repo that has a patch Arch's glibc to work with EAC
repo with the patch: https://github.com/Frogging-Family/glibc-eac/blob/main/disable_tests.patch
Arch's glibc recipe: https://github.com/archlinux/aur/blob/glibc-x86_64/PKGBUILD

**Comment by okawo80085** [comment]
Also as per this relatively ancient gentoo thread, building glibc with `libc_cv_hashstyle=no` made their EAC work again, but idk how relevant it is now
https://forums.gentoo.org/viewtopic-t-1147585.html?sid=ff98ea1836909e193ed668f5fd0430b5

I got glibc to build, but its inconsistant af, and if i try to link against the built libs instead of void-package ones steam refuses to start saying glibc has the wrong elfclass x)
So need to figure that one out before i can really do any proper testing :/

**Comment by nonchip** [comment]
@okawo80085 i'm rather positive that digging up already ruled out or clearly established things in a bunch of individual unedited spammy posts won't bring us further, please scroll next time. DT_HASH has been beaten to death and back now, and literally the 2nd post on this topic is about how flatpak works by not using our libc!

**Comment by atvexy** [comment]
i not sure if anyone has found a way (apart from Flatpaks) to launch eac successfully so i'm just posting this here in case it could lead to the root cause.

I found a way to launch vrchat successfully by forcing steam to run the game outside of it's "Steam Linux Runtime 3.0 (Sniper)" wrapper using vrchats launch options in steam. 

When you launch the game normally and watch steam clients output for the launch command it will be some form of `<steam path>/reaper -- <steam path>/steam-launch-wrapper -- <linux runtime path>/_v2-entry-point -- <proton path>/proton <vrchat path>/launch.exe`

This way vrchat fails to connect with eac and quits. When you copy the command and **remove** the Steam Runtime wrapper however (removing the `_v2-entry-point` while leaving the `reaper` and `steam-launch-wrapper`) and put the full command steam launch options (eg. `<steam path>/reaper -- <steam path>/steam-launch-wrapper -- <proton path>/proton <vrc path>/launch.exe # %command%`) the game and eac launches successfully.

This is a scuffed setup but it must likely rules out glibc from being the problem. It seams there's an issue when running an eac game inside the steam runtime as vrc couldn't even detect eac while its service was running in the background (logging `[AntiCheatClient] Anti-cheat client not available. Verify that the game was started using the anti-cheat bootstrapper if you intend to use it.`)

**Comment by dsemy** [comment]
This method works for Elden Ring and Armored Core 6, thanks.

**Comment by Dekomoro** [comment]
since it's narrowed to the runtime, I thought it might be worth bringing up this page. If special cases are needed they offer the ability to contact them. This was done with exherbo, which is another independent distro. https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/distro-assumptions.md

**Comment by Dekomoro** [comment]
So apparently the steam linux runtime calls all of it's scripts with #!/bin/sh.
I'm seriously suspecting some bashisms being the culprit here. I am not available right now for investigation so if someone could look into that as a possibility?

**Comment by classabbyamp** [comment]
you can run shellcheck on the scripts, maybe. some of the lints it raises are about bashisms in posix sh

**Comment by trizey** [comment]
> ```
> <steam path>/reaper -- <steam path>/steam-launch-wrapper -- <linux runtime path>/_v2-entry-point -- <proton path>/proton <vrchat path>/launch.exe
> ```

> ```
> <steam path>/reaper -- <steam path>/steam-launch-wrapper -- <proton path>/proton <vrc path>/launch.exe # %command%
> ```

Ran into this EAC issue this evening with Sea of Thieves and this workaround makes it playable again. Cheers for sharing it.

I'll try to contribute some time to this issue if its helpful, but I'm late to this party and getting caught up in this thread.

**Comment by Natthias** [comment]
Bashisms aren't the issue, symlinkg /bin/sh to bash doesn't fix EAC in my glibc chroot

**Comment by nonchip** [comment]
@trizey pretty sure that's something else, since Sea of Thieves never had *this* issue.

**Comment by trizey** [comment]
> @trizey pretty sure that's something else, since Sea of Thieves never had _this_ issue.

@nonchip Sea of Thieves enabled EAC recently in March. The error I was getting trying to login to the server was "EAC failed to initialize" to which the workaround mentioned in this thread fixes it. Seems pretty related to me.

**Comment by nonchip** [comment]
@trizey oh sorry yeah i haven't actually played in a few months, i wasn't aware that was new, thought they'd been using it for a while. yeah then it's related.

**Comment by okawo80085** [comment]
Tested again today on Void 6.6.29_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFF, EAC still fails with native steam, tested with VRChat and Insurgency, same errors as before `EAC failed to initialize`, all while the same games work fine on flatpak version on steam :/
If its not `glibc`, maybe its missing some shared lib dep or there is some dep version miss match?

**Comment by Norman-Normandy** [comment]
Don't know if this is relevant, but "nProtect GameGuard" for helldivers 2 works perfectly fine. Only EAC games don't work as they complain about hashing issues. Both the linker and libc.so appear to have both DT_GNU_HASH & DT_HASH symbols. I curious if there's something somehow preventing it from being reliably detected.

**Comment by okawo80085** [comment]
Just poping in to say that this is still very much an issue, except games like Insurgency stopped logging to console stuff like EAC status so its harder to debug now :melting_face:

**Comment by caszuu** [comment]
@okawo80085 did you try the workaround above or does eac not work at all? For me running eac outside of the runtime still works just as well.

From what i can tell with limited testing i did, the bug seems to be fully `pressure-vessel` related and can confirm that [umu](https://github.com/Open-Wine-Components/umu-launcher) also reproduces the same issue. (as it ships it's own steam linux runtime) I lack the skills to properly debug this but i wonder if it's some conflict between Void's fs structure and the path whitelist provided by `pressure-vessel` or something similar.

**Comment by Tyfuzzle** [comment]
@caszuu where do I get the command steam uses to launch a game from for the workaround? I can't see it in the steam terminal output and proton logs don't have anything (pretty sure it wouldn't be there since it's called mid-command, not before it).

**Comment by caszuu** [comment]
@Tyfuzzle huh i swear that steam used to print the command to stdout just a while ago, but i can't find it today either. One quick way to get the launch command is to start the game and get the command from `htop` in tree mode, the command your after is the `/bin/sh` one owning the game process

**Comment by Tyfuzzle** [comment]
@caszuu thanks. Got the command. It was showing in htop but the command was too long so I ended up doing this:
```
ps -ef | grep reaper
```

**Comment by okawo80085** [comment]
> @okawo80085 did you try the [workaround](https://github.com/void-linux/void-packages/issues/41388#issuecomment-1947357310) above or does eac not work at all? For me running eac outside of the runtime still works just as well.
> 
> From what i can tell with limited testing i did, the bug seems to be fully `pressure-vessel` related and can confirm that [umu](https://github.com/Open-Wine-Components/umu-launcher) also reproduces the same issue. (as it ships it's own steam linux runtime) I lack the skills to properly debug this but i wonder if it's some conflict between Void's fs structure and the path whitelist provided by `pressure-vessel` or something similar.

Hi, no i didn't, gonna try it in a bit

**Comment by okawo80085** [comment]
Ok so i tried it, a few notes, proposed fix forgot to mention that the proton command needed an additional argument and some environment variables setup to work correctly, the actual command ended up looking something like this for me
```
$STEAM_PATH/reaper -- $STEAM_PATH/steam-launch-wrapper -- $PROTON_PATH/proton run $APP_BIN
```
However this did not fix anything, i tested it with Insurgency Sandstorm, kicked from the match 5 minutes after start by EAC

Gonna try with VRChat later, but dont have much hope for it to work :L

**Comment by Naia-love** [comment]
> Ok so i tried it, a few notes, proposed fix forgot to mention that the proton command needed an additional argument and some environment variables setup to work correctly, the actual command ended up looking something like this for me
> ```
> $STEAM_PATH/reaper -- $STEAM_PATH/steam-launch-wrapper -- $PROTON_PATH/proton run $APP_BIN
> `

I dont know why you had to do that. I did the setup like monday to play and i didnt do anything than copy the command steam run, delete the v2 entry point part of it (and put in " " for the proton part as its proton 9 and it have a space in it path :^)

> However this did not fix anything, i tested it with Insurgency Sandstorm, kicked from the match 5 minutes after start by EAC
> 
> Gonna try with VRChat later, but dont have much hope for it to work :L 

Vrchat worked fine for me last time I tried. And i played elden ring online litteraly yesterday
its maybe because of what you changed?

**Comment by okawo80085** [comment]
Maybe it was because i was using Proton Experimental instead of Proton 9?

**Comment by okawo80085** [comment]
Noup, Proton 9 has the same arg parse, so i dont understand how you managed to start it without telling it to use `run` or any of the other available modes

**Comment by Naia-love** [comment]
> Noup, Proton 9 has the same arg parse, so i dont understand how you managed to start it without telling it to use `run` or any of the other available modes

and i dont understand why you need it x)
I could copy past you my steam launch option and you would just need to change to match your dir I suppose. Im not home tho rn

**Comment by okawo80085** [comment]
As for what i changed, it does not run without it, the mode argument for the proton script is not optional, without it it just fails with this funny error:
```
Proton: Need a verb.
```

**Comment by okawo80085** [comment]
>  I could copy past you my steam launch option and you would just need to change to match your dir I suppose. Im not home tho rn

Yeah why not, maybe i picked up the wrong proton folder lmao

**Comment by caszuu** [comment]
The example above is incomplete, sorry should have clarified that better... You should get the full command from steam the same as Tyfuzzle did above (steam used to print the command it used to launch the game but doesn't now)

The goal is to call the same command as steam would by default with the Linux runtime removed

**Comment by okawo80085** [comment]
Ohhhh, yeah that would explain it, what does the last `# %command%` do tho? Is it some more proton args or?

**Comment by Naia-love** [comment]
> Ohhhh, yeah that would explain it, what does the last `# %command%` do tho? Is it some more proton args or?

im not sure what the # do but the %command% tell steam its a command that need to be run before launching the game and not arguments to pass to the game executable

**Comment by caszuu** [comment]
It's what makes the original command from steam a shell comment as a way to deactivate it

It's explained on the [archwiki](https://wiki.archlinux.org/title/steam#Launch_options)

**Comment by okawo80085** [comment]
YOOOOOOOOOOOOOOOOOOOOOOOOO

It finally worked! Im gonna poke around with it a bit more, and if all is well i'll have a decent script that can launch stuff and not make EAC crash!

And i guess we can narrow this issue down to the linux sniper runtime that steam ships, the `_v2-entry-point` script in particular

**Comment by okawo80085** [comment]
Correction, Insurgency still does not work, however VRChat does? But only when launched using `launch.exe` instead of `VRChat.exe`

Script that i used to test looks like this
```bash
#!/bin/bash

STEAM_PATH="$HOME/.local/share/Steam/ubuntu12_32"
PROTON_PATH="$HOME/.local/share/Steam/steamapps/common/Proton - Experimental"
LINUX_RUNTIME_PATH="$HOME/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper"

APP_BIN=$2
APP_ID=$1

echo Launching \'$APP_BIN\' AppId=$APP_ID without _v2-entry-point...
echo

$STEAM_PATH/reaper SteamLaunch AppId=$APP_ID -- $STEAM_PATH/steam-launch-wrapper -- "$PROTON_PATH"/proton waitforexitandrun $APP_BIN
```

VRChat works fine if i launch it like this
```
./run_steam_without_v2_entry_point.sh 438100 ~/.steam/steam/steamapps/common/VRChat/launch.exe
```

However Insurgency does not work fine if i launch it in a similar fashion
```
./run_steam_without_v2_entry_point.sh 581320 ~/.steam/steam/steamapps/common/sandstorm/Insurgency.exe
```

**Comment by Naia-love** [comment]
> Correction, Insurgency still does not work, however VRChat does? But only when launched using `launch.exe` instead of `VRChat.exe`
> 
> Script that i used to test looks like this
> ```bash
> #!/bin/bash
> 
> STEAM_PATH="$HOME/.local/share/Steam/ubuntu12_32"
> PROTON_PATH="$HOME/.local/share/Steam/steamapps/common/Proton - Experimental"
> 
> APP_BIN=$2
> APP_ID=$1
> 
> echo Launching \'$APP_BIN\' AppId=$APP_ID without _v2-entry-point...
> echo
> 
> $STEAM_PATH/reaper SteamLaunch AppId=$APP_ID -- $STEAM_PATH/steam-launch-wrapper -- "$PROTON_PATH"/proton waitforexitandrun $APP_BIN
> ```
> 
> VRChat works fine if i launch it like this
> ```
> ./run_steam_without_v2_entry_point.sh 438100 ~/.steam/steam/steamapps/common/VRChat/launch.exe
> ```
> 
> However Insurgency does not work fine if i launch it in a similar fashion
> ```
> ./run_steam_without_v2_entry_point.sh 581320 ~/.steam/steam/steamapps/common/sandstorm/Insurgency.exe
> ```

be sure to launch the executable steam launch, there's high chance its actualy a "start protected.exe" or something like that (its the case on multiple eac game afaik)

**Comment by okawo80085** [comment]
Huh, well for Insurgency, the command that Steam uses is this
```
/home/okawo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=581320 -- /home/okawo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/okawo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /home/okawo/.local/share/Steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /home/okawo/.local/share/Steam/steamapps/common/sandstorm/InsurgencyEAC.exe
```
And that exe does not seem to want to launch without `_v2-entry-point` ???

**Comment by okawo80085** [comment]
And for those wondering to see the launch command put this into the launch options `echo %command% > /tmp/test.txt`

**Comment by caszuu** [comment]
> Huh, well for Insurgency, the command that Steam uses is this
> 
> ```
> /home/okawo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=581320 -- /home/okawo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/okawo/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /home/okawo/.local/share/Steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /home/okawo/.local/share/Steam/steamapps/common/sandstorm/InsurgencyEAC.exe
> ```
> 
> And that exe does not seem to want to launch without `_v2-entry-point` ???

I guess that makes sense since we're launching the game outside the expected runtime, so there's only a chance that a game will run outside of it.

After I get home, I'll try to sus out why the entry point is making eac panic, closest I got is that the `pressure-vessel` container itself is somehow blocking eac ([this](https://github.com/void-linux/void-packages/issues/41388#issuecomment-1949313480) is also useful if anyone is also digging)

**Comment by kshade** [comment]
Leaving out the runtime works for Halo Infinite as well!

**Comment by Tyfuzzle** [comment]
The fix was working for me last week on Halo MCC. Went back to it today and now I'm getting some EAC violation about an unknown file version. I think it might be more to do with Halo MCC than Void. I've seen threads about the same error from Windows users.

**Comment by fishslips** [comment]
So, this issue has been open for a year and a half. I'm new to void and really want to stick with it, but I think it's a bit wild that we still haven't sorted it out. Is there a way I can contribute or something to help get this sorted out?

**Comment by nonchip** [comment]
@fishslips sure, look at all the info gathered so far, gather any info you have ideas about, and try to figure out what the problem is, just like everyone else.

**Comment by fishslips** [comment]
Okay, so I did a proton log for the flatpak version of steam running The Finals which uses EAC as well as our xbps package for steam. 

[I created a gist here.](https://gist.github.com/fishslips/cab4b75c38b1d7cc917f069d81163f2f)

In both instances, anticheatlauncher.log in the prefix folder for the finals basically says Easy Anti-Cheat successfully loaded in-game, successfully initialized. There was no difference in the log for EAC when running in flatpak or xbps package. 

Both proton logs are fairly similar except for a few differences here and there (had to cut off most of the beginning of the files because it was over 100k lines), and mostly notably the end . The flatpak version continues as normal and it looks like Discovery.exe gets launched? Whereas the package version does not, renames some threads , says pids don't match, and it just abruptly stops.

**Comment by caszuu** [comment]
**TL;DR**: For now `GCONV_PATH="/usr/lib/gconv" %command%` in stream launch options should fix the issue.

---

After a day of mindless tracing, i was able to finally come to the cause of the issue. In short i used `bpftrace` to create a traces of all `open()` syscalls made by the app or eac. (similar to `strace` but without triggering eac) 

> All traces in this comment are logs from `bpftrace` of `open()` and `openat()` syscalls filtered for the processes and files in question. All testing was done on VRChat. Non-runtime in this comment means test ran without the steam linux runtime. (no `_v2_entry_point`)

I will try to sum it up in short and _hopefully_ in a way that make sense. (let me know if something's unclear)

### The crash

It turned out that the root of the issue was right when starting the game executable, specifically with eac bundled with the apps executable.

When you started VRChat non-runtime or on Arch Linux, the trace of the all _VRChat.exe_ `open()` syscalls looks similar to this: 
```
PID    COMM               FD ERR FLAGS PATH
1166   VRChat.exe          4   0 65536 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
1166   VRChat.exe          4   0 591872 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
1166   VRChat.exe         -1   2 524288 /home/caszu/.local/share/Steam/compatibilitytools.d/GE-Proton9-.. 
1166   VRChat.exe          4   0 524288 /usr/lib64/gconv/UTF-16.so 
1166   VRChat.exe          4   0 2048 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
1166   VRChat.exe          4   0 591872 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
1166   VRChat.exe         -1   2 524288 /home/caszu/.local/share/Steam/compatibilitytools.d/GE-Proton9-.. 
1166   VRChat.exe          4   0    0 /proc/self/maps 
1166   VRChat.exe          4   0  577 /tmp/eac_wine_pid_48E 
1166   VRChat.exe         15   0    0 . 
1166   VRChat.exe         16   0 591872 . 
1166   VRChat.exe         15   0    0 . 
...
```
> note: on Arch Linux `/usr/lib/gconv/UTF-16.so` is used instead of ` /usr/lib64/gconv/UTF-16.so `

This is the very start of _VRChat.exe_'s execution, it loads it's dependencies and a file `eac_wine_pid_<random>` is created.

**But** when VRChat is started on Void (in-runtime):
```
PID    COMM               FD ERR FLAGS PATH
2122   VRChat.exe          4   0 65536 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
2122   VRChat.exe          4   0 591872 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
2122   VRChat.exe         -1   2 524288 /home/caszu/.local/share/Steam/compatibilitytools.d/GE-Proton9-.. 
2122   VRChat.exe         -1   2 524288 /usr/share/locale/locale.alias      <-- no UTF-16.so loaded
2122   VRChat.exe         -1   2    0 /usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo 
2122   VRChat.exe         -1   2    0 /usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo 
2122   VRChat.exe         -1   2    0 /usr/share/locale/en_US/LC_MESSAGES/libc.mo 
2122   VRChat.exe         -1   2    0 /usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo 
2122   VRChat.exe         -1   2    0 /usr/share/locale/en.utf8/LC_MESSAGES/libc.mo 
2122   VRChat.exe         -1   2    0 /usr/share/locale/en/LC_MESSAGES/libc.mo 
2122   VRChat.exe          4   0 2048 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
2122   VRChat.exe          4   0 591872 /home/caszu/.local/share/Steam/steamapps/compatdata/438100/pfx/.. 
2122   VRChat.exe         -1   2 524288 /home/caszu/.local/share/Steam/compatibilitytools.d/GE-Proton9-.. 
2122   VRChat.exe         15   0    0 . 
2122   VRChat.exe         16   0 591872 . 
2122   VRChat.exe         15   0    0 . 
...
```
There are two differences, _VRChat.exe_ fails to find locales (fd that equals -1 means file not found) instead of loading the `UTF-16.so` lib and the `eac_wine_pid` file is never created which causes "The timeout" later.

As far as i can tell failing to find the locales for causes eac to silently die on the app side. (when launching at least)

This then probably tricks the app into thinking eac was never launched judging by the wording of the error in VRChats logs which sounds more "anti-cheat not found" than "anti-cheat triggered"
```
2024.07.13 18:55:16 Log        -  [EOSManager] [Info][LogEOSAntiCheat] [AntiCheatClient] Anti-cheat client not available. Verify that the game was started using the anti-cheat bootstrapper if you intend to use it.
```

The reason why _VRChat.exe_ does not load `UTF-16.so` in this case is unknown but probably related to the Steam runtime itself as there are multiple oddities with the runtime container, for example `/usr/lib/gconv` and `/usr/lib/locales/` inside the container are symlinked to equivalent host files but `/usr/lib64/gconv/` and `usr/lib64/locales/` are mostly empty directories. (you can test this by using [steam-runtime-launch-options](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md#using-steam-runtime-launch-options) to create a xterm shell inside the container)

Thankfully after defining `GCONV_PATH="/usr/lib/gconv"`, Void also starts working the same as other distros. (loading the `UTF-16.so` file)

I'm not sure which part of the stack (Void, Steam Runtime or eac) is to blame here or why, it might be steam if the `gconv` directory is improperly mapped or some missing env vars but i'm not sure. 

*So yeah, i don't know if i fell better or worse by knowing that a character conversion lib was to blame this whole time!*

### The timeout (extra info)

<details>

<summary><i>This is extra information not needed for the main explainer.</i></summary>

VRChat itself is made by three executable files: `launch.exe`, `start_protected.exe` and `VRChat.exe`

When VRChat launches, first _launch.exe_ is started and the eac service/driver loads, this is the file that shows you the eac loading screen. _start_protected.exe_ and _VRChat.exe_ are then started by _launch.exe_ after eac fully loads. (_VRChat.exe_ is the actual unity executable and _start_protected.exe_ is also a part of eac, _probably_)

When the _start_protected.exe_ is started, it waits for a creation of a file at `/tmp/eac_wine_pid_<random>`. It is supposed to be written by _VRChat.exe_ pretty much immediately after start and is deleted also immediately.

successful start from non-runtime trace and from an Arch Linux trace watching the eac file: (trimmed down)
```
PID    COMM               FD ERR FLAGS PATH
... bunch of start_protected opens ...
26702  start_protected    -1   2    0 /tmp/eac_wine_pid_6871 
26702  start_protected    -1   2    0 /tmp/eac_wine_pid_6871 
26702  start_protected    -1   2    0 /tmp/eac_wine_pid_6871 
26702  start_protected    -1   2    0 /tmp/eac_wine_pid_6871 
26737  VRChat.exe          4   0  577 /tmp/eac_wine_pid_6871 <-- eac from VRChat.exe creates the file  
26702  start_protected   129   0    0 /tmp/eac_wine_pid_6871 
26702  start_protected   129   0    0 /tmp/eac_wine_pid_6871 
26702  start_protected   129   0    0 /tmp/eac_wine_pid_6871 
26702  start_protected   129   0    0 /tmp/eac_wine_pid_6871 
26702  start_protected   129   0    0 /tmp/eac_wine_pid_6871 
...
```

**But** on Void this file is never created and _start_protected.exe_ "times out", which probably leaves eac in a confused state:
```
PID    COMM               FD ERR FLAGS PATH
...
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 
27489  start_protected    -1   2    0 /tmp/eac_wine_pid_6B83 // VRChat.exe is never seen
...
```

This might also be cause of the final eac failure instead of eac dying when starting _VRChat.exe_ but in any way is the root cause is eac dying when stating _VRChat.exe_.

</details>

**Comment by Naia-love** [comment]
Amazing work
I can confirm it work on my end for both VRC and EldenRing with this workaround
Thanks

**Comment by kshade** [comment]
> **TL;DR**: For now `GCONV_PATH="/usr/lib/gconv" %command%` in stream launch options should fix the issue.

Works for Halo Infinite as well, great work!

**Comment by oreo639** [comment]
Thank you for looking in to this. Our default gconv path is `/usr/lib{bits}/gconv`.
Testing it with `GCONV_PATH="/usr/lib64/gconv"` does not work whereas `GCONV_PATH="/usr/lib/gconv"` does.

Apparently this is because the `_v2-entry-point`/`pressure-vessel` container only exposes gconv modules though `/usr/lib` and `/usr/lib32` but not `/usr/lib64`.
https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/pressure-vessel/runtime.c#L5499-5654

**Comment by fanyx** [comment]
Wouldn't a simple symlink also solve this?

**Comment by classabbyamp** [comment]
`/usr/lib64` is a symlink to `/usr/lib` already

**Comment by oreo639** [comment]
> Wouldn't a simple symlink also solve this?

The pressure-vessel container exposes the host filesystem through `/run/host/`.
`/usr/` contains libraries bundled with the steam linux runtime with some other stuff such as the loader and the gconv modules being exposed though bubblewrap.

**Comment by okawo80085** [comment]
Great job @caszuu ! Adding `GCONV_PATH="/usr/lib/gconv" %command%`  fixed both VRChat and Insurgency for me!

**Comment by okawo80085** [comment]
Also prob worth tagging @kisak-valve, looks like there will have to be a patch for the env setup script, its either picking up gconv path wrong or the symlink is not working

**Comment by oreo639** [comment]
> Moderator on Github for Valve Software

Don't tag them, instead an issue should be made on the steam linux runtime gitlab.

**Comment by caszuu** [comment]
> Thank you for looking in to this. Our default gconv path is `/usr/lib{bits}/gconv`. Testing it with `GCONV_PATH="/usr/lib64/gconv"` does not work whereas `GCONV_PATH="/usr/lib/gconv"` does.
> 
> Apparently this is because the `_v2-entry-point`/`pressure-vessel` container only exposes gconv modules though `/usr/lib` and `/usr/lib32` but not `/usr/lib64`. https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/pressure-vessel/runtime.c#L5499-5654

hmm i still wonder if `/usr/lib64/gconv` not being symlinked is intentional or a mistake in the container, as `/usr/lib64/locale` **is** symlinked to `../lib/locale` but `/usr/lib64/gconv` (while it exists) is just a empty directory.

But at the same time VRC never even checked for the existence of gconv modules without `GCONV_PATH` being defined, trying to load locales instead. I'm probably missing how glibc works under the hood.

**Comment by oreo639** [comment]
> hmm i still wonder if `/usr/lib64/gconv` not being symlinked is intentional or a mistake in the container, as `/usr/lib64/locale` **is** symlinked to `../lib/locale` but `/usr/lib64/gconv` (while it exists) is just a empty directory.

Again, it is not supposed to be symlinked and the folders not being symlinked is intentional. The issue is that the 64-bit gconv modules are being bound to `/usr/lib/gconv` but not `/usr/lib64/gconv` which is most likely an oversight.

> VRC never even checked for the existence of gconv modules...

VRC isn't checking for gconv modules, glibc is through the `iconv()` API and `GCONV_PATH` allows you to specify extra paths to search beyond just the default one (`/usr/lib64/gconv` in this case).

**Comment by okawo80085** [comment]
> > Moderator on Github for Valve Software
> 
> Don't tag them here, instead an issue should be made on the steam linux runtime gitlab/github (which I can do later).

Please do

**Comment by cesorious** [comment]
This only seems to somewhat fix it for me, when trying to play elden ring for example, I now get past the "inapropriate activity", but when trying to log in I get "Connection to epic online  services failed: 01-00000", but that might just be a wholy independent issue.
However, EAC also doesn't work in brawlhalla

**Comment by oreo639** [comment]
This issue should be resolved in the latest SLR. https://github.com/ValveSoftware/steam-runtime/issues/680#issuecomment-2299563781
