### ISSUE TITLE
xbps-src package ghc-bin troubles

### ISSUE THREAD

**Issue by RicardoKovd** [void-linux/void-packages#54891]
I found that the ghc version in the repository is a bit low, and I want to try to maintain it. I had a problem when building ghc-bin. I installed the .xbps packaged with the upstream https://downloads.haskell.org/ghc/9.8.4/ghc-9.8.4-x86_64-deb12-linux.tar.xz. This problem occurred
```bash
$ xbps-install -R hostdir/binpkgs ghc-bin-9.8.4_1
ghc-bin-9.8.4_1: broken, unresolvable shlib `libtinfo.so.6'
Transaction aborted due to unresolved shlibs.
```
I wandered around this problem for several hours without any clue. I would like to get some help.
My uname
```bash
$ xuname
Void 6.12.18_1 x86_64 AuthenticAMD notuptodate rFF
```
My template
```bash
# Template file for 'ghc-bin'
pkgname=ghc-bin
version=9.8.4
revision=1
archs="i686 x86_64* ppc64le* ppc64 aarch64*"
hostmakedepends="perl libffi libnuma"
depends="ncurses perl gcc libffi-devel gmp-devel"
short_desc="Glorious Haskell Compiler - precompiled binaries"
maintainer="Orphaned <orphan@voidlinux.org>"
license="BSD-3-Clause"
homepage="http://www.haskell.org/ghc/"
nocross=yes
nostrip=yes
noshlibprovides=yes
conflicts="ghc>=0 ghc-doc>=0"
distfiles="https://downloads.haskell.org/ghc/${version%[!0-9]}/ghc-${version}-x86_64-deb12-linux.tar.xz"
checksum=b50545b54934068a569225e3dde267a8b5aab66449330d63e02a8cf28972375e

do_configure() {
	./configure --prefix=/usr
}

do_install() {
	export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH

	make install DESTDIR="$DESTDIR"

	vlicense "$DESTDIR/usr/share/doc/${XBPS_TARGET_MACHINE}-linux-ghc-${version%[!0-9]}/ghc-${version%[!0-9]}/LICENSE"
}

```
Steps to reproduce
```bash
$ ./xbps-src pkg ghc-bin
...
$ xbps-install -R hostdir/binpkgs ghc-bin
ghc-bin-9.8.4_1: broken, unresolvable shlib `libtinfo.so.6'
Transaction aborted due to unresolved shlibs.
```

**Comment by Chocimier** [comment]
ncurses-libtinfo-libs was missing necessary metadata, fixed in 6.5_2 .

ghc runs, but emits some warning: `/usr/lib/ghc-9.8.4/bin/./ghc-9.8.4: /usr/lib64/libtinfo.so.6: no version information available (required by /usr/lib/ghc-9.8.4/bin/../lib/x86_64-linux-ghc-9.8.4/libHShaskeline-0.8.2.1-1d49-ghc9.8.4.so)`

**Comment by Arkissa** [comment]
> ncurses-libtinfo-libs was missing necessary metadata, fixed in 6.5_2 .
> 
> ghc runs, but emits some warning: `/usr/lib/ghc-9.8.4/bin/./ghc-9.8.4: /usr/lib64/libtinfo.so.6: no version information available (required by /usr/lib/ghc-9.8.4/bin/../lib/x86_64-linux-ghc-9.8.4/libHShaskeline-0.8.2.1-1d49-ghc9.8.4.so)`

Is this due to a problem with my packaging steps? @Chocimier

**Comment by RicardoKovd** [comment]
> ncurses-libtinfo-libs was missing necessary metadata, fixed in 6.5_2 .
> 
> ghc runs, but emits some warning: `/usr/lib/ghc-9.8.4/bin/./ghc-9.8.4: /usr/lib64/libtinfo.so.6: no version information available (required by /usr/lib/ghc-9.8.4/bin/../lib/x86_64-linux-ghc-9.8.4/libHShaskeline-0.8.2.1-1d49-ghc9.8.4.so)`

Is this due to a problem with my packaging steps? @Chocimier

**Comment by Chocimier** [comment]
it's not, see #54241

**Comment by RicardoKovd** [comment]
> it's not, see [#54241](https://github.com/void-linux/void-packages/issues/54241)  它不是，见 [#54241](https://github.com/void-linux/void-packages/issues/54241)

I added this flag to ncurses according to this issue #54241, but I still get this error.
```diff
do_configure() {
	export CFLAGS="$CFLAGS -fPIC"
	export BUILD_CFLAGS="$BUILD_CFLAGS -fPIC"

	mkdir -p ncurses-build ncursesw-build

	cd ${wrksrc}/ncursesw-build
	# widec build
	../configure ${configure_args} \
		--with-shared --without-debug \
+		--with-versioned-syms \
		--with-manpage-symlinks --with-manpage-format=normal \
		--without-ada --enable-ext-colors --with-xterm-kbs=del \
		--without-tests --enable-pc-files \
		--with-pkg-config-libdir=/usr/lib/pkgconfig \
		ac_cv_path_ac_pt_PKG_CONFIG=/usr/bin/pkg-config \
		PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig \
		BUILD_CFLAGS="$BUILD_CFLAGS"

	cd ${wrksrc}/ncurses-build
	# non-widec build
	../configure ${configure_args} --with-shared \
+		--with-versioned-syms \
		--disable-widec --without-debug --without-ada --without-tests --with-xterm-kbs=del \
		--enable-pc-files --with-pkg-config-libdir=/usr/lib/pkgconfig \
		ac_cv_path_ac_pt_PKG_CONFIG=/usr/bin/pkg-config \
		PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig \
		BUILD_CFLAGS="$BUILD_CFLAGS"
}
```
I made sure I was using ncurses from host/binpkgs, not the remote repository
```diff
=> ghc-bin-9.8.4_1: building for x86_64...
   [host] perl-5.40.1_1: found (https://repo-default.voidlinux.org/current)
   [host] libffi-3.3_2: found (https://repo-default.voidlinux.org/current)
   [host] libnuma-2.0.18_1: found (https://repo-default.voidlinux.org/current)
-   [runtime] ncurses-6.5_1: found ([/host/binpkgs](https://repo-default.voidlinux.org/current))
+   [runtime] ncurses-6.5_1: found (/host/binpkgs)
   [runtime] perl-5.40.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] gcc-13.2.0_3: found (https://repo-default.voidlinux.org/current)
   [runtime] libffi-devel-3.3_2: found (https://repo-default.voidlinux.org/current)
   [runtime] gmp-devel-6.3.0_1: found (https://repo-default.voidlinux.org/current)
```
but still give me this error @Chocimier 
```cmdline
[xchroot masterdir-x86_64] # xbps-query ncurses
...
pkgname: ncurses
pkgver: ncurses-6.5_1
provides:
	cmd:clear-6.5_1
	cmd:infocmp-6.5_1
	cmd:tabs-6.5_1
	cmd:tic-6.5_1
	cmd:toe-6.5_1
	cmd:tput-6.5_1
	cmd:tset-6.5_1
repository: /binpkgs
run_depends:
	ncurses-base-6.5_1
	ncurses-libs-6.5_1
	glibc>=2.39_1
shlib-requires:
	libc.so.6
	libncursesw.so.6
...
[xchroot masterdir-x86_64] # xbps-install -R /binpkgs ghc-bin
ghc-bin-9.8.4_1: broken, unresolvable shlib `libtinfo.so.6'
Transaction aborted due to unresolved shlibs.
```

**Comment by RicardoKovd** [comment]
Sorry, I misunderstood what you meant. I added ncurses-libtinfo-libs-6.5_2 dependency and it works now.
